apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sentryflow
  name: log-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-client
  template:
    metadata:
      labels:
        app: log-client
    spec:
      containers:
      - name: log-client
        image: 5gsec/sentryflow-log-client:v0.1
        env:
        - name: SERVER_ADDR
          value: "sentryflow.sentryflow.svc.cluster.local"
        - name: SERVER_PORT
          value: "8080"
        - name: LOG_CFG
          value: "stdout"
        - name: METRIC_CFG
          value: "stdout"
        - name: METRIC_FILTER
          value: "api"
