apiVersion: v1
kind: Namespace
metadata:
  name: sentryflow
  labels:
    istio-injection: disabled # avoid Istio sidecar injection
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-sentryflow
  namespace: sentryflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-sentryflow
rules:
- apiGroups: ["*"]
  verbs: ["*"]
  resources: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rb-sentryflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-sentryflow
subjects:
- kind: ServiceAccount
  name: sa-sentryflow
  namespace: sentryflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentryflow
  namespace: sentryflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentryflow
  template:
    metadata:
      labels:
        app: sentryflow
    spec:
      serviceAccountName: sa-sentryflow
      containers:
      - name: sentryflow
        image: 5gsec/sentryflow:v0.1
        ports:
        - containerPort: 4317
          protocol: TCP
          name: grpc-otlp
        - containerPort: 8080
          protocol: TCP
          name: grpc-export
---
apiVersion: v1
kind: Service
metadata:
  name: sentryflow
  namespace: sentryflow
spec:
  selector:
    app: sentryflow
  ports:
    - protocol: TCP
      port: 4317
      targetPort: 4317
      name: grpc-otlp
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: grpc-export
