header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: SentryFlow
    content: |
      SPDX-License-Identifier: Apache-2.0

  paths:
    - "**/*.go"
    - "**/Dockerfile"
    - "**/Makefile"

  paths-ignore:
    - "protobuf/*"
    # Explicitly mention generated go files otherwise the check won't pass.
    - "protobuf/**/*.go"

  comment: on-failure

dependency:
  files:
    - go.mod
