#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Authors of SentryFlow

if ! command -v addlicense >/dev/null; then
  echo "Installing addlicense..."
  go install github.com/google/addlicense@latest
fi

GIT_ROOT=$(git rev-parse --show-toplevel)
LICENSE_HEADER=${GIT_ROOT}/hack/license.header

if [ -z "$1" ]; then
  echo "No Argument Supplied, Checking and Fixing all files from project root"
  find "${GIT_ROOT}" -name "*.sh" -or -name "*.go" | xargs -I {} addlicense -f "${LICENSE_HEADER}" -v {}
  echo "Done"
else
  addlicense -f "${LICENSE_HEADER}" -v "$1"
  echo "Done"
fi
