// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: sentryflow_metrics.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type APIClassificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *APIClassificationRequest) Reset() {
	*x = APIClassificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sentryflow_metrics_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIClassificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIClassificationRequest) ProtoMessage() {}

func (x *APIClassificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentryflow_metrics_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIClassificationRequest.ProtoReflect.Descriptor instead.
func (*APIClassificationRequest) Descriptor() ([]byte, []int) {
	return file_sentryflow_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *APIClassificationRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type APIClassificationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Merged string   `protobuf:"bytes,1,opt,name=merged,proto3" json:"merged,omitempty"`
	Fields []string `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *APIClassificationResponse) Reset() {
	*x = APIClassificationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sentryflow_metrics_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIClassificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIClassificationResponse) ProtoMessage() {}

func (x *APIClassificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentryflow_metrics_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIClassificationResponse.ProtoReflect.Descriptor instead.
func (*APIClassificationResponse) Descriptor() ([]byte, []int) {
	return file_sentryflow_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *APIClassificationResponse) GetMerged() string {
	if x != nil {
		return x.Merged
	}
	return ""
}

func (x *APIClassificationResponse) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_sentryflow_metrics_proto protoreflect.FileDescriptor

var file_sentryflow_metrics_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x6d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x22, 0x2e, 0x0a, 0x18, 0x41, 0x50, 0x49, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x22, 0x4b, 0x0a, 0x19, 0x41, 0x50, 0x49, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x32, 0x78, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x46, 0x6c, 0x6f, 0x77, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x63, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x50, 0x49,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x50, 0x49, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x50,
	0x49, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x15, 0x5a, 0x13, 0x73,
	0x65, 0x6e, 0x74, 0x72, 0x79, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sentryflow_metrics_proto_rawDescOnce sync.Once
	file_sentryflow_metrics_proto_rawDescData = file_sentryflow_metrics_proto_rawDesc
)

func file_sentryflow_metrics_proto_rawDescGZIP() []byte {
	file_sentryflow_metrics_proto_rawDescOnce.Do(func() {
		file_sentryflow_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(file_sentryflow_metrics_proto_rawDescData)
	})
	return file_sentryflow_metrics_proto_rawDescData
}

var file_sentryflow_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sentryflow_metrics_proto_goTypes = []interface{}{
	(*APIClassificationRequest)(nil),  // 0: protobuf.APIClassificationRequest
	(*APIClassificationResponse)(nil), // 1: protobuf.APIClassificationResponse
}
var file_sentryflow_metrics_proto_depIdxs = []int32{
	0, // 0: protobuf.SentryFlowMetrics.GetAPIClassification:input_type -> protobuf.APIClassificationRequest
	1, // 1: protobuf.SentryFlowMetrics.GetAPIClassification:output_type -> protobuf.APIClassificationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sentryflow_metrics_proto_init() }
func file_sentryflow_metrics_proto_init() {
	if File_sentryflow_metrics_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sentryflow_metrics_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIClassificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sentryflow_metrics_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIClassificationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sentryflow_metrics_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sentryflow_metrics_proto_goTypes,
		DependencyIndexes: file_sentryflow_metrics_proto_depIdxs,
		MessageInfos:      file_sentryflow_metrics_proto_msgTypes,
	}.Build()
	File_sentryflow_metrics_proto = out.File
	file_sentryflow_metrics_proto_rawDesc = nil
	file_sentryflow_metrics_proto_goTypes = nil
	file_sentryflow_metrics_proto_depIdxs = nil
}
