# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Authors of SentryFlow

filters:
  server:
    port: 8081

  envoy:
    uri: anuragrajawat/httpfilter:v0.1

receivers: # aka sources
  serviceMeshes:
    - name: istio-sidecar
      namespace: istio-system
exporter:
  grpc:
    port: 8080
