apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sentryflow.fullname" . }}
  labels:
    {{- include "sentryflow.labels" . | nindent 4 }}
    {{- with .Values.genericLabels }}
          {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
  - apiGroups:
      - networking.istio.io
    verbs:
      - get
      - create
      - delete
    resources:
      - envoyfilters
  - apiGroups:
      - extensions.istio.io
    verbs:
      - get
      - create
      - delete
    resources:
      - wasmplugins

  - apiGroups:
      - ""
    verbs:
      - get
      - update
    resources:
      - configmaps
  - apiGroups:
      - ""
    verbs:
      - list
    resources:
      - services
  - apiGroups:
      - apps
    verbs:
      - get
      - update
    resources:
      - deployments
