apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "sentryflow.fullname" . }}
  labels:
    {{- include "sentryflow.labels" . | nindent 4 }}
    {{- with .Values.genericLabels }}
          {{- toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "sentryflow.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sentryflow.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
