apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentryflow.fullname" . }}
  labels:
    {{- include "sentryflow.labels" . | nindent 4 }}
    {{- with .Values.genericLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "sentryflow.selectorLabels" . | nindent 4 }}
