# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Authors of SentryFlow

filters:
  server:
    port: 8081

# Envoy filter is required for `istio-sidecar` service-mesh receiver.
#  envoy:
#    uri: 5gsec/sentryflow-httpfilter:latest

#  Following is required for `nginx-inc-ingress-controller` receiver.
#  nginxIngress:
#    deploymentName: nginx-ingress-controller
#    configMapName: nginx-ingress
#    sentryFlowNjsConfigMapName: sentryflow-njs

receivers: # aka sources
# Uncomment the following receivers according to your requirement.

#  serviceMeshes:
#    - name: istio-sidecar
#      namespace: istio-system

#  others:
#    - name: nginx-inc-ingress-controller
#      namespace: default

#    - name: nginx-webserver

exporter:
  grpc:
    port: 8080
