filters:
  server:
    port: 8081

  envoy:
    uri: anuragrajawat/httpfilter:v0.1

receivers: # aka sources
  serviceMeshes:
    - name: istio-sidecar
      namespace: istio-system
  others: # TBD
    - name: "coroot"
      # Either gRPC or HTTP not both
      grpc:
        url: localhost
        port: 1234
      http:
        url: localhost
        port: 4321

exporter:
  grpc:
    port: 8080
