name: ci-test-py
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  py-pip-ai-sentryflow:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: check Python pip3 requirements
        run: |
          pip install -r requirements.txt
        working-directory: ai-engine

  py-lint-ai-sentryflow:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ai-engine
  
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff --output-format=github .
        continue-on-error: true
        working-directory: ai-engine

  py-pep8-ai-sentryflow:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: 'Run PEP8'
        uses: quentinguidee/pep8-action@v1
        with:
          arguments: '--max-line-length=120'    